/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./api/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Fruit: { // root type
    _id?: string | null; // ID
    description?: string | null; // String
    limit?: number | null; // Int
    name?: string | null; // String
  }
  Mutation: {};
  Query: {};
  Storage: { // root type
    _id?: string | null; // ID
    amount?: number | null; // Int
    fruit?: string | null; // ID
    name?: string | null; // String
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Fruit: { // field return type
    _id: string | null; // ID
    description: string | null; // String
    limit: number | null; // Int
    name: string | null; // String
  }
  Mutation: { // field return type
    createFruit: NexusGenRootTypes['Fruit']; // Fruit!
    deleteFruit: boolean; // Boolean!
    updateFruit: NexusGenRootTypes['Fruit']; // Fruit!
    updateStorage: NexusGenRootTypes['Storage']; // Storage!
  }
  Query: { // field return type
    fruits: Array<NexusGenRootTypes['Fruit'] | null>; // [Fruit]!
    storage: Array<NexusGenRootTypes['Storage'] | null> | null; // [Storage]
  }
  Storage: { // field return type
    _id: string | null; // ID
    amount: number | null; // Int
    fruit: string | null; // ID
    name: string | null; // String
  }
}

export interface NexusGenFieldTypeNames {
  Fruit: { // field return type name
    _id: 'ID'
    description: 'String'
    limit: 'Int'
    name: 'String'
  }
  Mutation: { // field return type name
    createFruit: 'Fruit'
    deleteFruit: 'Boolean'
    updateFruit: 'Fruit'
    updateStorage: 'Storage'
  }
  Query: { // field return type name
    fruits: 'Fruit'
    storage: 'Storage'
  }
  Storage: { // field return type name
    _id: 'ID'
    amount: 'Int'
    fruit: 'ID'
    name: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createFruit: { // args
      description: string; // String!
      limit: number; // Int!
      name: string; // String!
    }
    deleteFruit: { // args
      fruitId: string; // ID!
    }
    updateFruit: { // args
      description?: string | null; // String
      fruitId: string; // ID!
      limit?: number | null; // Int
      name?: string | null; // String
    }
    updateStorage: { // args
      amount: number; // Int!
      fruit: string; // ID!
      name: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}